name: Metrics

on:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.recent.svg
          token: ${{ secrets.token1 }}
          base: ""
          plugin_languages: "yes"
          plugin_languages_ignored: "html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot"
          plugin_languages_sections: "recently-used"
          plugin_languages_details: "bytes-size, percentage"
          plugin_languages_limit: 4
