name: Recently used languages metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  generate_recent_languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate recently used languages SVG
        uses: lowlighter/metrics@latest
        with:
          # Use o nome do seu segredo aqui
          token: ${{ secrets.token1 }}
          
          filename: metrics.plugin.languages.recent.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
