name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with write permissions
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # permite push

      - name: Prepare output directory
        run: mkdir -p output

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: manoper93
          outputs: |
            output/github-contribution-grid-snake.svg

      - name: Show output folder contents for debug
        run: ls -l output

      - name: Check git status before commit
        run: git status

      - name: Commit and push only if changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/github-contribution-grid-snake.svg
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Generate contribution snake"
            git push origin HEAD:main
          fi
